# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# ## Sessions
# :new<CR>  new session
# s  list sessions
# $  name session
# # Windows (tabs)
# c new window
# , name window
# w list windows
# f find window
# & kill window
# . move window - prompted for a new number
# :movew<CR>  move window to the next unused number
# ## Panes (splits)
# %  horizontal split
# "  vertical split
# o  swap panes
# q  show pane numbers
# x  kill pane
# ⍽  space - toggle between layouts

set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm*:Tc"

bind r source-file ~/.tmux.conf

set -sg escape-time 1
set -g history-limit 10000
set -g mouse on
setw -g mode-keys vi

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
run -b '~/.tmux/plugins/tpm/tpm'

set -g @emulate-scroll-for-no-mouse-alternate-buffer 'on'
set -g @yank_action 'copy-pipe' # or 'copy-pipe-and-cancel' for the default

#set -g status-bg default
#set -g status-fg white 
set -g update-environment "SSH_AUTH_SOCK"
set-environment -g 'SSH_AUTH_SOCK' ~/.ssh/ssh_auth_sock
