#plugin https://github.com/sxyazi/yazi/tree/shipped/yazi-config/preset
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
[manager]
# ratio = [0, 4, 4]
ratio = [2, 4, 3]

[opener]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
  { run = 'code %*', orphan = true, desc = "code", for = "windows" },
  { run = 'code -w %*', block = true, desc = "code (block)", for = "windows" },
]
open = [
  { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
  { run = 'termux-open "$1"', desc = "Open", for = "android" },
]
reveal = [
  { run = 'tmux new-window -c "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  # { run = 'nautilus "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = 'termux-open "$(dirname "$1")"', desc = "Reveal", for = "android" },
  { run = '''clear; exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
  { run = '7ze "$@"', desc = "Extract Subdir", for = "unix" },
  { run = 'ya pub extract --list %*', desc = "Extract here", for = "windows" },
]
play = [
  { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
  { run = 'mpv --force-window %*', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[open]
rules = [
  # Folder
  { name = "*/", use = [
    "edit",
    "open",
    "reveal",
  ] },
  # Text
  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  # Image
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  # Media
  { mime = "{audio,video}/*", use = [
    "play",
    "reveal",
  ] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
    "extract",
    "reveal",
  ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },
  # Empty file
  { mime = "inode/empty", use = [
    "edit",
    "reveal",
  ] },
  # Fallback
  { name = "*", use = [
    "open",
    "reveal",
  ] },
]

[plugin]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]

prepend_previewers = [
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
  { name = "*zip", run = "ouch" },
  # { name = "*.md", run = "glow" },
]
append_previewers = [{ name = "*", run = "hexyl" }]
